
name = "DatamedCustomComponents"
uuid = "1b08a953-4be3-4667-9a23-dac39930aa3d"
authors = ["jmunozz <j1805@hotmail.com>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
